# -*- coding: utf-8 -*-
"""Uber data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YogStoEy78sEkNhuAEktP6ZKrF241veK

# UBER DATA ANALYSIS
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df = pd.read_csv("/Uber Drives - .csv")



df.head()

df

df.dtypes

import datetime
import calendar

df.isnull().sum()

df.isnull().any()

data = df.copy()

data.head()

data = data.dropna()

data.isnull().any()

data["START_DATE*"] = pd.to_datetime(data["START_DATE*"] , format = '%m/%d/%Y %H:%M')

data["END_DATE*"] = pd.to_datetime(data["END_DATE*"] , format = '%m/%d/%Y %H:%M')

data.dtypes

hour = []
day = []
month = []
weekdays =[]
dayofweek = []



for x in data["START_DATE*"]:
  hour.append(x.hour)
  month.append(x.month)
  day.append(x.day)
  dayofweek.append(x.dayofweek)
  weekdays.append(calendar.day_name[dayofweek[-1]])

data['HOUR'] = hour
data['DAY'] = day
data['MONTH'] = month
data['WEEKDAYS'] = weekdays
data['DAYOFWEEK'] = dayofweek

data.head()

"""**CATEGORIES WE HAVE**"""

data['CATEGORY*'].value_counts()

sns.countplot(x= 'CATEGORY*',data = data)

"""**How long do people travel with uber**"""

data['MILES*'].plot.hist()

"""**PURPOSE OF THE TRIPS**"""

data['PURPOSE*'].value_counts().plot(kind = 'bar',figsize = (10,5),color = 'brown')

"""**WHICH DAT HAS THE HIGHEST NUMBER OF TRIP**"""

data['WEEKDAYS'].value_counts().plot(kind = 'bar',figsize = (10,5),color = 'yellow')

"""**WHAT hour do most people take uber during their destination**"""

hours = data['START_DATE*'].dt.hour.value_counts()
hours.plot(kind = 'bar',figsize=(10,5),color = 'black')
plt.xlabel('HOUR')
plt.ylabel('Frequency')
plt.title("Number of trips vs hours")

"""**what are the number of trips per each day**"""

data['DAY'].value_counts().plot(kind = 'bar',figsize = (10,5),color = 'blue')

"""**WHAT ARE THE TRIPS IN THE MONTH**"""

data['MONTH'].value_counts().plot(kind = 'bar',figsize = (10,5),color = 'red')

"""**THE STARTING POINT OF THE TRIP WHERE DO PEOPLE START BOARDING THEIR TRIP THE MOST**"""

data['START*'].value_counts().plot(kind = 'bar',figsize = (25,5),color = 'blue')